" OS specific ----
if has("gui_macvim")
  set guioptions-=T " remove toolbar
  set guifont=Monaco:h13
  set stal=2 " turn on tabs by default
  set bg=dark
  if &background == "dark"
    highlight normal guibg=black
    set transparency=8
  endif
elseif has("gui_win32")
  " TODO: add win32-specific stuff from home machine
end

" General settings ----

" anti-aliased fonts
set anti 

" Tab headings (evaluate these to see if I like them?)
set gtl=%t gtt=%F
